Add enhanced training script
IBM/MAX-Spatial-Transformer-Network pull request #9
Opened 2018-09-19 01:26 UTC by djalova

Address #8

2018-10-19 19:21 UTC, ptitzler reviewed
I was able to train the model with the latest fix.

2018-10-19 19:21 UTC, ptitzler commented on train.sh
> +  donegit s
Breaks the script.

2018-10-19 19:25 UTC, ptitzler commented
Since you are already touching the repo, could you please also update the readme to: 

- use `ibmcloud` (new name)  instead of  `bx` (old name)
- fix the formatting issue (last bullet in section "Setup an IBM Cloud Object Storage (COS) account")

2018-10-19 20:52 UTC, djalova commented
Sure, I can update those. I'm not sure what the formatting issue is in the last bullet though.

2018-10-19 21:31 UTC, ptitzler commented
<img width="1338" alt="screen shot 2018-10-19 at 2 19 24 pm" src="https://user-images.githubusercontent.com/13068832/47244745-79bb8180-d3ab-11e8-808b-928bc8d12fde.png">
" - Export ..." looks like it was supposed to be a new item on the bulleted list?

2018-10-19 21:41 UTC, djalova commented
Oh thanks for catching. The markdown preview on my editor displays it fine. I'll look into it.

2018-10-22 22:26 UTC, ptitzler commented on README.md
> +	- From the bluemix console page (https://console.bluemix.net/dashboard/apps/) choose `Cloud Object Storage`
> From the bluemix console
From the IBM Cloud console

2018-10-22 22:29 UTC, ptitzler commented on README.md
> +	- From the bluemix console page (https://console.bluemix.net/dashboard/apps/) choose `Cloud Object Storage`
Looks like you missed one instance of `bx` in the scoring section. If you could also add a `$` prefix to each code snippet that people need to run in a terminal window to clearly distinguish it from output:

> bx ml score scoring-payload.json

$ ibmcloud ml score scoring-payload.json

2018-10-23 17:50 UTC, ptitzler requested changes
Having read the Watson Studio documentation I believe finally understand why the model code was ZIPed up in the first place. We'll need to discuss how to proceed.

2019-05-13 08:28 UTC, closed without merging